Layout/DotPosition:
  Enabled:            false

Layout/ExtraSpacing:
  Enabled:            false

Layout/IndentHeredoc:
  Enabled:            false

Performance/RegexpMatch:
  Enabled:            false

Style/ConstantVisibility:
  Enabled:            false

Style/InlineComment:
  Enabled:            false

Style/SymbolArray:
  EnforcedStyle:      'brackets'

Style/OptionHash:
  Enabled:            false

Security/YAMLLoad:
  Enabled:            false
