inherit_from:
  - '.rubocop_core.yml'

# Put your project-specifc Rubocop config here

AllCops:
  TargetRubyVersion: 1.9

Style/SymbolArray:
  EnforcedStyle: 'brackets'

Style/OptionHash:
  Enabled: false

Style/IndentationWidth:
  Enabled: false

Style/ExtraSpacing:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Exclude:
    - 'spec/**/*.rb'

Security/YAMLLoad:
  Enabled: false
